### ISSUE TITLE
How to resume the ckpt

### ISSUE THREAD

**Issue by zimingzhong** [DSaurus/threestudio-3dgs#13]
i run `python launch.py --config custom/threestudio_3dgs/configs/gaussian_splatting.yaml --train --gpu 0 resume=/mnt/nas/zzm/proj/threestudio/outputs/gs-sds-generation/a_delicious_hamburger@20231225-175858/ckpts/last.ckpt`

and get 

`(4d) root@dsw71134-767ffb954b-wp7tq:/mnt/nas/zzm/proj/threestudio# python launch.py --config custom/threestudio_3dgs/configs/gaussian_splatting.yaml --train --gpu 0 resume=/mnt/nas/zzm/proj/threestudio/outputs/gs-sds-generation/a_delicious_hamburger@20231225-175858/ckpts/last.ckpt
/opt/conda/envs/4d/lib/python3.9/site-packages/controlnet_aux/mediapipe_face/mediapipe_face_common.py:7: UserWarning: The module 'mediapipe' is not installed. The package will have limited functionality. Please install it using the command: pip install 'mediapipe'
  warnings.warn(
/opt/conda/envs/4d/lib/python3.9/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_5m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_5m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/opt/conda/envs/4d/lib/python3.9/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_11m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_11m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/opt/conda/envs/4d/lib/python3.9/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/opt/conda/envs/4d/lib/python3.9/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_384 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_384. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/opt/conda/envs/4d/lib/python3.9/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_512 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_512. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
Traceback (most recent call last):
  File "/mnt/nas/zzm/proj/threestudio/launch.py", line 62, in load_custom_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "custom/threestudio_3dgs/__init__.py", line 1, in <module>
    from .background import gaussian_mvdream_background
  File "custom/threestudio_3dgs/background/gaussian_mvdream_background.py", line 15, in <module>
    class NeuralEnvironmentMapBackground(BaseBackground):
  File "/mnt/nas/zzm/proj/threestudio/threestudio/__init__.py", line 9, in decorator
    raise ValueError(
ValueError: Module gaussian-mvdream-neural-environment-map-background already exists! Names of extensions conflict!

Cannot import custom/threestudio_3dgs module for custom nodes: Module gaussian-mvdream-neural-environment-map-background already exists! Names of extensions conflict!

Import times for custom modules:
   0.0 seconds: custom/__init__.py
   0.0 seconds (IMPORT FAILED): custom/threestudio_3dgs

Traceback (most recent call last):
  File "/mnt/nas/zzm/proj/threestudio/launch.py", line 302, in <module>
    main(args, extras)
  File "/mnt/nas/zzm/proj/threestudio/launch.py", line 164, in main
    cfg = load_config(args.config, cli_args=extras, n_gpus=n_gpus)
  File "/mnt/nas/zzm/proj/threestudio/threestudio/utils/config.py", line 113, in load_config
    scfg = parse_structured(ExperimentConfig, cfg)
  File "/mnt/nas/zzm/proj/threestudio/threestudio/utils/config.py", line 127, in parse_structured
    scfg = OmegaConf.structured(fields(**cfg))
  File "/opt/conda/envs/4d/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 375, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/opt/conda/envs/4d/lib/python3.9/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/opt/conda/envs/4d/lib/python3.9/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/opt/conda/envs/4d/lib/python3.9/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/opt/conda/envs/4d/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 369, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/opt/conda/envs/4d/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 451, in _get_impl
    return self._resolve_with_default(
  File "/opt/conda/envs/4d/lib/python3.9/site-packages/omegaconf/basecontainer.py", line 96, in _resolve_with_default
    raise MissingMandatoryValue("Missing mandatory value: $FULL_KEY")
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: tag
    full_key: tag
    object_type=dict`

**Comment by DSaurus** [comment]
Hi @zimingzhong ,

I noticed that you have `custom/__init__.py` in your custom directory, which may lead to the error `Module gaussian-mvdream-neural-environment-map-background already exists! Names of extensions conflict!`.

**Comment by zimingzhong** [comment]
> Hi @zimingzhong ,
> 
> I noticed that you have `custom/__init__.py` in your custom directory, which may lead to the error `Module gaussian-mvdream-neural-environment-map-background already exists! Names of extensions conflict!`.

I comment all codes in 'custom/__init__.py' and re-run the code.

`(4d) root@dsw71134-767ffb954b-wp7tq:/mnt/nas/zzm/proj/threestudio# python launch.py --config custom/threestudio_3dgs/configs/gaussian_splatting_background.yaml --train --gpu 0 resume=/mnt/nas/zzm/proj/threestudio/outputs/gs-sds-generation-background/a_crocodile_playing_a_drum_set@20231226-140532/ckpts/last.ckpt
/opt/conda/envs/4d/lib/python3.9/site-packages/controlnet_aux/mediapipe_face/mediapipe_face_common.py:7: UserWarning: The module 'mediapipe' is not installed. The package will have limited functionality. Please install it using the command: pip install 'mediapipe'
  warnings.warn(
/opt/conda/envs/4d/lib/python3.9/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_5m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_5m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/opt/conda/envs/4d/lib/python3.9/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_11m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_11m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/opt/conda/envs/4d/lib/python3.9/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/opt/conda/envs/4d/lib/python3.9/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_384 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_384. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/opt/conda/envs/4d/lib/python3.9/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_512 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_512. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)

Import times for custom modules:
   0.0 seconds: custom/threestudio_3dgs

Traceback (most recent call last):
  File "/mnt/nas/zzm/proj/threestudio/launch.py", line 302, in <module>
    main(args, extras)
  File "/mnt/nas/zzm/proj/threestudio/launch.py", line 164, in main
    cfg = load_config(args.config, cli_args=extras, n_gpus=n_gpus)
  File "/mnt/nas/zzm/proj/threestudio/threestudio/utils/config.py", line 113, in load_config
    scfg = parse_structured(ExperimentConfig, cfg)
  File "/mnt/nas/zzm/proj/threestudio/threestudio/utils/config.py", line 127, in parse_structured
    scfg = OmegaConf.structured(fields(**cfg))
  File "/opt/conda/envs/4d/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 375, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/opt/conda/envs/4d/lib/python3.9/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/opt/conda/envs/4d/lib/python3.9/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/opt/conda/envs/4d/lib/python3.9/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/opt/conda/envs/4d/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 369, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/opt/conda/envs/4d/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 451, in _get_impl
    return self._resolve_with_default(
  File "/opt/conda/envs/4d/lib/python3.9/site-packages/omegaconf/basecontainer.py", line 96, in _resolve_with_default
    raise MissingMandatoryValue("Missing mandatory value: $FULL_KEY")
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: tag
    full_key: tag
    object_type=dict`

**Comment by DSaurus** [comment]
Okay, I think you should add the text prompt when resuming the ckpt.
