### ISSUE TITLE
NameError: name 'gaussian_3d_coeff' is not defined

### ISSUE THREAD

**Issue by zjjgogogo** [DSaurus/threestudio-3dgs#21]
When I try to export mesh, it goes this:

Traceback (most recent call last):
  File "launch.py", line 301, in <module>
    main(args, extras)
  File "launch.py", line 259, in main
    trainer.predict(system, datamodule=dm, ckpt_path=cfg.resume)
  File "/root/miniconda3/envs/threestudio/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in predict
    return call._call_and_handle_interrupt(
  File "/root/miniconda3/envs/threestudio/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/miniconda3/envs/threestudio/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 903, in _predict_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/root/miniconda3/envs/threestudio/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 989, in _run
    results = self._run_stage()
  File "/root/miniconda3/envs/threestudio/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1030, in _run_stage
    return self.predict_loop.run()
  File "/root/miniconda3/envs/threestudio/lib/python3.8/site-packages/pytorch_lightning/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/root/miniconda3/envs/threestudio/lib/python3.8/site-packages/pytorch_lightning/loops/prediction_loop.py", line 128, in run
    return self.on_run_end()
  File "/root/miniconda3/envs/threestudio/lib/python3.8/site-packages/pytorch_lightning/loops/prediction_loop.py", line 200, in on_run_end
    results = self._on_predict_epoch_end()
  File "/root/miniconda3/envs/threestudio/lib/python3.8/site-packages/pytorch_lightning/loops/prediction_loop.py", line 358, in _on_predict_epoch_end
    call._call_lightning_module_hook(trainer, "on_predict_epoch_end")
  File "/root/miniconda3/envs/threestudio/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 157, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/root/threestudio/threestudio/systems/base.py", line 332, in on_predict_epoch_end
    exporter_output: List[ExporterOutput] = self.exporter()
  File "/root/threestudio/custom/threestudio-3dgs/geometry/exporter.py", line 35, in __call__
    mesh: Mesh = self.geometry.extract_mesh()
  File "/root/threestudio/custom/threestudio-3dgs/geometry/gaussian_io.py", line 267, in extract_mesh
    occ = self.extract_fields(resolution).detach().cpu().numpy()
  File "/root/miniconda3/envs/threestudio/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/threestudio/custom/threestudio-3dgs/geometry/gaussian_io.py", line 246, in extract_fields
    w = gaussian_3d_coeff(
NameError: name 'gaussian_3d_coeff' is not defined

**Comment by taoranyi** [comment]
look this https://github.com/DSaurus/threestudio-3dgs/blob/4eb76e19aae09d597d0fed67faf031a1db21ea18/geometry/gaussian_base.py#L63

**Comment by lighten001** [comment]
> look this
> 
> https://github.com/DSaurus/threestudio-3dgs/blob/4eb76e19aae09d597d0fed67faf031a1db21ea18/geometry/gaussian_base.py#L63

when import gaussian_3d_coeff from gaussian_base.py, will occur
```shell
ImportError: cannot import name 'gaussian_3d_coeff' from partially initialized module 'threestudio-3dgs.geometry.gaussian_base' (most likely due to a
 circular import) (/data/wlp/projects/diffusion/threestudio/custom/threestudio-3dgs/geometry/gaussian_base.py)
```

in my opinion, there are some useful functions/classes in gaussian_base.py, like ``gaussian_3d_coeff``, ``BasicPointCloud`` and ``Camera``, etc. maybe should move these functions/classes to a independ file.

whats more, maybe can move some of them (like ``BasicPointCloud``) to threestudio repo. (cause ``BasicPointCloud`` is essential for building a new extension, and importing cross extension is very sophisticated.

**Comment by Gotta-C** [comment]
move gaussian_3d_coeff to gaussian_io.py
